package com.xecoder.core.entity;

import com.xecoder.config.BaseEntity;

import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

@Table(name = "security_role_permission")
public class RolePermission extends BaseEntity implements Serializable{
    /** 
	 * @description: 
	 * @version 1.0
	 * @author ZHEJIANG RUIZHENG
	 * @createDate 2014-1-19;下午10:50:12
	 */
	private static final long serialVersionUID = 4299904046947533203L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column security_role_permission.id
     *
     * @mbggenerated
     */

    @Id
    @Column(name = "id")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column security_role_permission.permission_id
     *
     * @mbggenerated
     */
    private Long permissionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column security_role_permission.role_id
     *
     * @mbggenerated
     */
    private Long roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column security_role_permission.id
     *
     * @return the value of security_role_permission.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column security_role_permission.id
     *
     * @param id the value for security_role_permission.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column security_role_permission.permission_id
     *
     * @return the value of security_role_permission.permission_id
     *
     * @mbggenerated
     */
    public Long getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column security_role_permission.permission_id
     *
     * @param permissionId the value for security_role_permission.permission_id
     *
     * @mbggenerated
     */
    public void setPermissionId(Long permissionId) {
        this.permissionId = permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column security_role_permission.role_id
     *
     * @return the value of security_role_permission.role_id
     *
     * @mbggenerated
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column security_role_permission.role_id
     *
     * @param roleId the value for security_role_permission.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    @Transient
    private Permission permission;

    @Transient
    private List<RolePermissionDataControl> rolePermissionDataControls;

	public Permission getPermission() {
		return permission;
	}

	public void setPermission(Permission permission) {
		this.permission = permission;
	}

	public List<RolePermissionDataControl> getRolePermissionDataControls() {
		return rolePermissionDataControls;
	}

	public void setRolePermissionDataControls(
			List<RolePermissionDataControl> rolePermissionDataControls) {
		this.rolePermissionDataControls = rolePermissionDataControls;
	}
    
}