package com.xecoder.core.mapper;

import com.xecoder.config.MybatisMapper;
import com.xecoder.core.entity.DataControl;
import com.xecoder.core.entity.DataControlCriteria;
import com.xecoder.core.entity.User;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface DataControlMapper extends MybatisMapper<User> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_data_control
     *
     * @mbggenerated
     */
    int countByExample(DataControlCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_data_control
     *
     * @mbggenerated
     */
    int deleteByExample(DataControlCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_data_control
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_data_control
     *
     * @mbggenerated
     */
    int insert(DataControl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_data_control
     *
     * @mbggenerated
     */
    int insertSelective(DataControl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_data_control
     *
     * @mbggenerated
     */
    List<DataControl> selectByExample(DataControlCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_data_control
     *
     * @mbggenerated
     */
    DataControl selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_data_control
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DataControl record, @Param("example") DataControlCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_data_control
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DataControl record, @Param("example") DataControlCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_data_control
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DataControl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_data_control
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DataControl record);
}