package com.xecoder.core.mapper;

import com.xecoder.config.MybatisMapper;
import com.xecoder.core.entity.Module;
import com.xecoder.core.entity.ModuleCriteria;
import com.xecoder.core.entity.User;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface ModuleMapper extends MybatisMapper<User> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_module
     *
     * @mbggenerated
     */
    int countByExample(ModuleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_module
     *
     * @mbggenerated
     */
    int deleteByExample(ModuleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_module
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_module
     *
     * @mbggenerated
     */
    int insert(Module record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_module
     *
     * @mbggenerated
     */
    int insertSelective(Module record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_module
     *
     * @mbggenerated
     */
    List<Module> selectByExample(ModuleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_module
     *
     * @mbggenerated
     */
    Module selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_module
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Module record, @Param("example") ModuleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_module
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Module record, @Param("example") ModuleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_module
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Module record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_module
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Module record);
}