package com.xecoder.core.mapper;

import com.xecoder.config.MybatisMapper;
import com.xecoder.core.entity.Organization;
import com.xecoder.core.entity.OrganizationCriteria;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface OrganizationMapper extends MybatisMapper<Organization> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_organization
     *
     * @mbggenerated
     */
    int countByExample(OrganizationCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_organization
     *
     * @mbggenerated
     */
    int deleteByExample(OrganizationCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_organization
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_organization
     *
     * @mbggenerated
     */
    int insert(Organization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_organization
     *
     * @mbggenerated
     */
    int insertSelective(Organization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_organization
     *
     * @mbggenerated
     */
    List<Organization> selectByExample(OrganizationCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_organization
     *
     * @mbggenerated
     */
    Organization selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_organization
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Organization record, @Param("example") OrganizationCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_organization
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Organization record, @Param("example") OrganizationCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_organization
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Organization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_organization
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Organization record);

    /**
     * 查找登录用户所在部门
     * @param userId
     * @return
     * @author maoni
     */
    List<Organization> findByUser(@Param("userId") Long userId);
}