package com.xecoder.core.mapper;

import com.xecoder.config.MybatisMapper;
import com.xecoder.core.entity.RolePermission;
import com.xecoder.core.entity.RolePermissionCriteria;
import com.xecoder.core.entity.User;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface RolePermissionMapper extends MybatisMapper<User> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_role_permission
     *
     * @mbggenerated
     */
    int countByExample(RolePermissionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_role_permission
     *
     * @mbggenerated
     */
    int deleteByExample(RolePermissionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_role_permission
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_role_permission
     *
     * @mbggenerated
     */
    int insert(RolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_role_permission
     *
     * @mbggenerated
     */
    int insertSelective(RolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_role_permission
     *
     * @mbggenerated
     */
    List<RolePermission> selectByExample(RolePermissionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_role_permission
     *
     * @mbggenerated
     */
    RolePermission selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_role_permission
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RolePermission record, @Param("example") RolePermissionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_role_permission
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RolePermission record, @Param("example") RolePermissionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_role_permission
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_role_permission
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RolePermission record);
}